[package]
name = "arcra"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.6.0"
axum = { version = "0.8.9", features = ["macros"] }
axum-extra = { version = "0.12.6", features = ["form"] }
base64 = "0.23.1"
chrono = { version = "0.4.45", features = ["serde"] }
serde = "1.0.229"
sqlx = { version = "0.9.0", features = ["chrono", "runtime-tokio", "sqlite"] }
tera = { version = "2.4.0", features = ["fast", "glob_fs"] }
tokio = { version = "1.53.1", features = ["full"] }
tower-cookies = { version = "0.11.0", features = ["private"] }
